#version: '3'
#
#services:
#  mysqldb:
#    image: mysql
#    restart: always
#    environment:
#      MYSQL_DATABASE: 'family'
#      MYSQL_USER: 'user'
#      MYSQL_PASSWORD: 'password'
#      MYSQL_ROOT_PASSWORD: 'password'
#    ports:
#      - '3306:3306'
#    expose:
#      - '3306'
#
#  app:
#    depends_on:
#      - mysqldb
#    build:
#      context: ./
#      dockerfile: Dockerfile
#    image: family-server:latest
#    ports:
#      - '8080:8080'
#    networks:
#      -family-familymember-network:
#networks:
#  -family-familymember-network:
#    driver: bridge